#!/bin/bash
# Script to remove obsolete dual-mode templates
# Generated by AP Orchestrator for clean native architecture

echo "Removing obsolete dual-mode compatibility templates..."

DUAL_MODE_DIR="/mnt/c/Code/agentic-persona-mapping/installer/templates/claude/agents/dual-mode"

if [ -d "$DUAL_MODE_DIR" ]; then
    echo "Found dual-mode directory: $DUAL_MODE_DIR"
    echo "Removing 5 large compatibility templates:"
    echo "  - migration-pathway.md.template (1,084 lines)"
    echo "  - compatibility-validation.md.template (1,016 lines)"  
    echo "  - mode-transition-engine.md.template (910 lines)"
    echo "  - subagent-integration.md.template (883 lines)"
    echo "  - dual-mode-orchestration.md.template (531 lines)"
    
    rm -rf "$DUAL_MODE_DIR"
    
    if [ $? -eq 0 ]; then
        echo "✅ Successfully removed dual-mode directory"
        echo "✅ Removed 4,424+ lines of obsolete compatibility code"
        echo "✅ APM now has clean native-only architecture"
    else
        echo "❌ Error removing dual-mode directory"
        exit 1
    fi
else
    echo "✅ Dual-mode directory already removed or not found"
fi

echo "✅ Dual-mode cleanup complete"